### ISSUE TITLE
Bot users will be unsupported from March 31, 2025

### ISSUE THREAD

**Issue by nekosoft** [jenkinsci/slack-plugin#1041]
### Describe your use-case which is not covered by existing documentation.

Bot users are considered legacy as of June 2024, and will stop working March 31, 2025. **This means that the Slack App will need to be recreated without a bot user.** 

I was writing a Slack App and happened to come across documentation regarding manifest fields and bot users. In this project's README manifest, a bot user is defined with permissions. They are also inherently insecure in design. Slack has also developed many different ways to write integrations, so now they're trying to simplify but give greater security control with granular permissions. 

If you require user interaction, this can be achieved with "interactions": https://api.slack.com/interactivity/handling

Depending on the functionality, it might affect the implementation but I haven't read through to find out where just yet - that's why I've chosen _Documentation_ for issue type, reassign it to something else if it needs to be.

https://github.com/jenkinsci/slack-plugin/blob/master/README.md

```yaml
display_information:
  name: Jenkins
features:
  bot_user:
    display_name: Jenkins
    always_online: true
oauth_config:
  scopes:
    bot:
      - channels:read
      - chat:write
      - chat:write.customize
      - files:write
      - reactions:write
      - users:read
      - users:read.email
      - groups:read
settings:
  org_deploy_enabled: false
  socket_mode_enabled: false
  token_rotation_enabled: false
```

Also, token_rotation_enabled is set to false, is there a reason for this? Is it not supported?

I haven't had a chance to look into Interactions yet but I thought it would be good to flag this in case you're not already aware (I couldn't see a branch working on it). I suspect a lot of people's plugins will break.

### Reference any relevant documentation, other materials or issues/pull requests that can be used for inspiration.

https://github.com/jenkinsci/slack-plugin/blob/master/README.md

Legacy bots will be unsupported March 31, 2025: https://api.slack.com/legacy/enabling-bot-users

### Are you interested in contributing to the documentation?

Yes I am interested, I am still reading the documentation. If someone is already working on it or has the knowledge, then it's best they follow through as there isn't long.
