### ISSUE TITLE
Slack publish failed, response code 404

### ISSUE THREAD

**Issue by amit-o** [jenkinsci/slack-plugin#480]
I'm trying to setup slack integration on a docker running in localhost.
When trying to publish or test connection in the settings, I'm getting this in the logs:

> Jan 17, 2019 9:37:55 AM jenkins.plugins.slack.StandardSlackService publish
> WARNING: Slack post may have failed. Response: null
> Jan 17, 2019 9:37:55 AM jenkins.plugins.slack.StandardSlackService publish
> WARNING: Response Code: 404

The same configurations are working in a non-docker configurations
```

    slackNotifier:
      tokenCredentialId: slack-token
      teamDomain: <workspace>
      baseUrl: https://<workspace>.slack.com/services/hooks/jenkins-ci/  
 credentials:
    system:
      domainCredentials:
            - string:
                scope: GLOBAL
                id: slack-token
                secret: ${SLACK_TOKEN}
```
