### ISSUE TITLE
How to Sanity-Check Slack Plugin Configuration via Jenkins Configuration as Code

### ISSUE THREAD

**Issue by jamiejackson** [jenkinsci/slack-plugin#531]
I'm having trouble with this configuration, and I'd like to know what the simplest way of knowing whether my CasC is working for this plugin.

```yml
unclassified:
  slackNotifier:
    room: "#bot_notifications"
    teamDomain: "${SLACK_TEAM_DOMAIN}"
    tokenCredentialId: slack_integration_token
```
Is there, say, somewhere I can go in the Jenkins GUI to see that these items have been correctly populated? Otherwise, what's the simplest way?
