### ISSUE TITLE
slackUserIdsFromCommitters(botUser: true) is crashing

### ISSUE THREAD

**Issue by mariadb-JeffBachtel** [jenkinsci/slack-plugin#739]
### Your checklist for this issue

- [X] Jenkins version 2.249.2

- [X] Plugin version 2.43

- [X] OS Cloudbees Jenkins docker hub container

### Description

Please see https://gist.github.com/mariadb-JeffBachtel/5d934194bc21c0290d4964271132339e for a gist of the FINE logs around the problem

```
java.lang.UnsupportedOperationException: Refusing to marshal org.apache.http.impl.client.InternalHttpClient for security reasons; see https://jenkins.io/redirect/class-filter/
```

My pipeline is running on a Kubernetes cloud executor, and not on the master node, if that makes a difference. I'll whitelist the method in question and test as well, but it seemed unlikely others were hitting this.

**Comment by timja** [comment]
don't whitelist it

**Comment by timja** [comment]
hmm from what I can tell the client should be constructed on the agent already.

this seems to somehow be an interaction with the configuration-as-code plugin.

![image](https://user-images.githubusercontent.com/21194782/97918546-30e68380-1d4e-11eb-9c3e-0041a2c3fa32.png)

can you reliably reproduce this?

cc @jetersen

**Comment by mariadb-JeffBachtel** [comment]
Yes, with "reliably" doing some lifting (I only have 1 pipeline I'm testing the Slack plugin on. The Slack plugin is configured via JCasC. This crash happens every time there is a changeset, but not when a pipeline is rerun with no changes)

The config as code snippet (from Jenkins console)
```
unclassified:
    slackNotifier:
    botUser: true
    room: "ci-cd"
    sendAsText: false
    slackUserIdResolver: "email"
    teamDomain: "myslackdomain"
    tokenCredentialId: "slack-token"
```
